# GNU Make solution makefile autogenerated by Premake
# Type "make help" for usage help

ifndef config
  config=debug
endif
export config

PROJECTS := tankgame-tn13

.PHONY: all clean help $(PROJECTS)

all: $(PROJECTS)

tankgame-tn13: 
	@echo "==== Building tankgame-tn13 ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f tankgame-tn13.make

clean:
	@${MAKE} --no-print-directory -C . -f tankgame-tn13.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "   debug"
	@echo "   release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   tankgame-tn13"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"
